### ISSUE TITLE
Questions about generation of CAR reference

### ISSUE THREAD

**Issue by yulicarp** [getzlab/Haradhvala_et_al_2022#1]
Hi,

thanks for this amazing work and also for making the code public.

I have some questions about generation of CAR reference:
1. In initial reference, what are the sequences of pELPs 19-BBz for tisa-cel? is it just CD19-BBzeta CAR nucleic acid sequence or plus pELPs-CD19-BBz transfer vector sequence?
2. Why do we need to further refine the reference sequence instead of using the initial reference?
3. Why you choose four infusion product samples to refine reference not all samples?

**Comment by njharlen** [comment]
Hi,

Thanks for your kind words, hope this helps:

1. It includes the full vector sequence, many reads align upstream of scFv in the 5' UTR, so important to at least include that (the rest of the vector backbone doesn't really matter but we included it anyway to see if anything would align).
2. Because the initial reference was an imperfect estimation of the CAR sequence based on patent literature, and we found it to have a small number of point mutations and indels relative to the actual data. We corrected these just to make sure they didn't cause any issues with alignment . 
3. Just because they were the first four samples we sequenced, the CAR sequences are the same for all samples so there was no reason to redo it once we had additional samples.

**Comment by yulicarp** [comment]
Thanks for your reply! 

Sorry to bother you again, could you tell me where i can download the full vector sequence?  
I could only found the vector diagram in patent or article as shown below. Do I need to build this vector sequence myself using SnapGene?

Thanks in advance for your kind help!
![car-t](https://github.com/getzlab/Haradhvala_et_al_2022/assets/68860278/a2213ee2-d703-4bb7-a8d9-1591a0460df2)
> https://patents.google.com/patent/WO2012079000A1/en
> https://www.nejm.org/doi/suppl/10.1056/NEJMoa1103849/suppl_file/nejmoa1103849_protocol.pdf

Kind regards,
Yu Li

**Comment by njharlen** [comment]
Hi Yu,

They have the sequence as part of the patent, see here:
https://www.lens.org/lens/patent/175-246-371-138-874/sequences/view/1

Also if you're only interested in tisa-cel you may not need to do any sequence correction, most mismatches with our initial estimate came from axi-cel. Though worth checking the alignment in any case. 

Nick
