### ISSUE TITLE
Question related to h5 object

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [getzlab/Haradhvala_et_al_2022#2]
Hello, Thank you for sharing the h5 raw object . I would like to extract extract the cell ids that are defined as CD4 and CD8 T cells respectively. Can you please explain which layer has this information or how i can extract this information ? Please share. Thanks.

**Comment by Krithika-Bhuvan** [comment]
Not sure if this is right
```
adata = sc.read("<add path here>")

cell_type_summary = adata.obs['cell_type'].value_counts()
print(cell_type_summary)

# If CD4 and CD8 T cells are already annotated in adata.obs['cell_type']
cd4_cells = adata.obs_names[adata.obs['cell_type'] == 'CD4 T']
cd8_cells = adata.obs_names[adata.obs['cell_type'] == 'CD8 T']

# Convert to lists if needed
cd4_cell_ids = cd4_cells.tolist()
cd8_cell_ids = cd8_cells.tolist()

print("CD4 T cells:", cd4_cell_ids)
print("CD8 T cells:", cd8_cell_ids)
```

**Comment by njharlen** [comment]
Hi Krithika,

I would suggest using the results of our knn-based classification, which can be found in the "subtype" column or the following metadata table in our google drive:
https://drive.google.com/file/d/1IBhfFcnWUcM6fpeE66biKcaAE-y7gmBB/view?usp=drive_link

The "cell_type" column is our cell type annotations based on leiden clustering shown in Fig. 1, however we found sometimes CD4+ CTLs (which are infrequent for overall T-cells, but can be very large percents of a given patients CAR-T cells specifically) would cluster with the CD8s and thus get misclassified by this approach. That's why for downstream analyses we did a more supervised classification of CD4/8s using our "feux flow" approach illustrated in Ext data figure 4d.

**Comment by Krithika-Bhuvan** [comment]
Thank you very much for the quick response and for sharing the right metadata file ! I will use the "subtype" column from this metadata file and extract the cell ids accordingly.

**Comment by Krithika-Bhuvan** [comment]
Hello @njharlen , I have one more question. The cell ids in the metadata file are in the form of 
`AAACCTGAGAAGATTC-1-0`. I'm guessing the rightmost number is the sample index
Where can i get the mapping of these sample indexes ? Just want to make sure i match the right sample index with the right sample id. 
The `sample` column has ids in a different form "Axi-R-03-Infusion" , so that's not the one to use.

**Comment by njharlen** [comment]
In many cases we pooled together samples to run on a single 10x channel, so those digits would correspond to the 10x run which is named in the "channel" column. But the indices of adata.obs and the metadata should match up, so you shouldn't need to do any of this mapping on your end.

**Comment by Krithika-Bhuvan** [comment]
Thank you so much for the additional clarification. You are saying that the last number (0 in this case) matches with the "channel" column. "AAACCTGAGAAGATTC-1-0"
I will use the metadata as advised. In our use case, we are interested in a sub-set of samples so I will filter based on the  metadata. Appreciate the quick response.
